### ISSUE TITLE
Error on ESM TypeScript project when using ts-node + mocha

### ISSUE THREAD

**Issue by lostvicking** [Typescript-TDD/ts-auto-mock#1094]
### Error is thrown when running mocha tests 
ESM TypeScript project is being tested with Mocha, when `ts-auto-mock`'s `createMock` is called an error is thrown 

### Your environment
* ts-auto-mock version: 3.5.0 
* typescript version: 4.6.2 
* node version: 14.17.6
* npm version: 8.4.1 
* mocha version: 9.2.2
* ts-node version: 10.7.0 

### Steps to reproduce
Example repo here: https://github.com/lostvicking/esm-ts-auto-mock-example 
Run `npm test` 

### Expected behavior
Expect `createMock` to generate a mock of specified type without errors. 

### Actual behavior
An error is thrown:
```
Error:
  hey, it looks like ts-auto-mock is not configured correctly! You can find the instructions here https://typescript-tdd.github.io/ts-auto-mock/installation.
  If you need further assistance feel free to drop a message on slack. (link at the bottom of https://typescript-tdd.github.io/ts-auto-mock)

    at r.createMock (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/ts-auto-mock/index.js:1:502)
    at file:///Users/victorneiman/Code/esm-ts-auto-mock-example/tests/test.ts:5:26
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async formattedImport (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/victorneiman/Code/esm-ts-auto-mock-example/node_modules/mocha/lib/cli/run.js:374:5)
```

**Comment by uittorio** [comment]
Hello, 

I did not forget about this, just being busy with the family, and decided not to spend time on ts-auto-mock. 

Anyway, it has been 2 months 🤣 

I couldn't fix the problem or find the root cause yet but I've checkout out your repo and I've realised that it was not configured correctly, or at least the transformer was not running at all. Instead of using the example provided by ts-auto-mock I've installed ts-patch to run the transformer.

this unfortunately gave me another error
```TypeError: Cannot read properties of undefined (reading 'instance')
    at file:///Users/{username}/repos/esm-ts-auto-mock-example/tests/test.ts:5:25
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
➜  esm-ts-auto-mock-example git:(master) ✗ 
```

**Comment by CarsonF** [comment]
I just hit this. It's because the transformer generates a namespaced import, when actually a default import is needed.

https://github.com/Typescript-TDD/ts-auto-mock/blob/master/src/typescriptFactory/typescriptFactory.ts#L442-L455

Changing to this generates correctly:
```ts
core.ts.factory.createImportClause(false, moduleName)
```
Though obv that would need to be conditional.
