### ISSUE TITLE
typescript 3.8.2 support

### ISSUE THREAD

**Issue by uittorio** [Typescript-TDD/ts-auto-mock#245]
I was trying to use typescript 3.8.2 in a gatbsy project.
I had an error  when adding a mock in a test
``` 
TypeError: Cannot read property 'kind' of null
      at isEmitNotificationEnabled (node_modules/typescript/lib/typescript.js:92020:52)
      at getPipelinePhase (node_modules/typescript/lib/typescript.js:93199:96)
      at pipelineEmit (node_modules/typescript/lib/typescript.js:93188:33)
      at emit (node_modules/typescript/lib/typescript.js:93166:30)
      at emitFunctionDeclarationOrExpression (node_modules/typescript/lib/typescript.js:94680:13)
      at emitFunctionExpression (node_modules/typescript/lib/typescript.js:94252:13)
      at pipelineEmitWithHint (node_modules/typescript/lib/typescript.js:93582:32)
      at pipelineEmitWithSourceMap (node_modules/typescript/lib/typescript.js:96727:21)
      at pipelineEmitWithComments (node_modules/typescript/lib/typescript.js:96471:17)
      at pipelineEmit (node_modules/typescript/lib/typescript.js:93189:13)
```

I've attached the code that caused the issue.

[typescript-3.8.2-issue.zip](https://github.com/Typescript-TDD/ts-auto-mock/files/4269911/typescript-3.8.2-issue.zip)

**Comment by uittorio** [comment]
I’ve done some initial investigation.

There are not supposed to be breaking change in version 3.8.

The issue is when we create function expression and we pass empty array as default value instead of undefined. Ive tried to change it to undefined and it works.

**Comment by uittorio** [comment]
a new version has been published. 1.5.7 with the support of typescript 3.8
