### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ColinCee** [Typescript-TDD/ts-auto-mock#557]
### Subject of the issue
After upgrading from v2.0.0 to v2.6.3 this started happening.

Highly likely related to https://github.com/Typescript-TDD/ts-auto-mock/issues/498 as I tried upgrading to typescript v4 and it worked fine.

### Your environment
* ts-auto-mock version: 2.6.3
* typescript version: 3.9.2
* node version: 12.18.3
* npm version: 6.14.6
* list any other dependencies that you think are relevant

### Steps to reproduce
Here's an example but really any doesn't run 

```ts
const voiceConnection = createMock<VoiceConnection>();
    jest
      .spyOn(VC, "getBotVoiceConnection")
      .mockReturnValueOnce(Promise.resolve(null))
      .mockReturnValueOnce(Promise.resolve(voiceConnection));

    const result = await joinVoiceChannel(message);
    expect(JVC.JoinVoiceChannel.prototype.execute).toBeCalled();
    expect(result).toBe(voiceConnection);
```
[Specific commit](https://github.com/WeLoveRice/twitch-bot/commit/90e43a2988750aa9f4a6c4851e5055b639d7ee7f)

### Expected behavior
Tests should pass

### Actual behavior

```ts
    TypeError: Cannot read property 'map' of undefined

      at Object.t.GetTupleDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:87836)
      at Object.t.GetDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:4228)
      at Object.t.GetMethodDeclarationDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:41728)
      at Object.t.GetDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:3349)
      at node_modules/ts-auto-mock/transformer/index.js:1:56504
          at Array.reduce (<anonymous>)
      at Object.t.GetMockPropertiesAssignments (node_modules/ts-auto-mock/transformer/index.js:1:56474)
      at f (node_modules/ts-auto-mock/transformer/index.js:1:22213)
      at Object.t.GetMockPropertiesFromSymbol (node_modules/ts-auto-mock/transformer/index.js:1:22366)
      at Object.t.GetProperties (node_modules/ts-auto-mock/transformer/index.js:1:25012)
```

**Comment by Pmyl** [comment]
Hi, could you tell me where does the type "VoiceConnection" comes from so that I can test it locally?

**Comment by ColinCee** [comment]
Hey, it's from [discord.js](https://github.com/discordjs/discord.js), I'm using `v12.3.1`

**Comment by Pmyl** [comment]
We made a mistake when upgrading typescript version, I'm sorry.
We're going to do 2 things:
- new patch version with a bug fix to support both typescript 4 and typescript 3
- new major version to end the support to typescript 3 and only support 4+
I should be able to do that by today (it's morning here).

**Comment by Pmyl** [comment]
The release died for some reason, I'll fix something else and we will have the fix for this released correctly

**Comment by Pmyl** [comment]
@ColinCee let me know if the new version works :D
