### ISSUE TITLE
Mocking getters from class with mobx annotations

### ISSUE THREAD

**Issue by dziadyk-m** [Typescript-TDD/ts-auto-mock#739]
Hey,

I'm not pretty sure if it is a feature or bug, but actually it isn't possible to create mock on class which have getter annotated by mobx computed annotation. 

Test suite failed to run

    TypeError: Cannot read property 'kind' of undefined

      at Object.isComputedPropertyName (node_modules/typescript/lib/typescript.js:11303:21)
      at Object.e.GetStringPropertyName (node_modules/ts-auto-mock/transformer/index.js:1:21026)
      at node_modules/ts-auto-mock/transformer/index.js:1:37025
      at node_modules/ts-auto-mock/transformer/index.js:1:37117
     at Array.reduce (<anonymous>)
      at Object.t.GetMockPropertiesAssignments (node_modules/ts-auto-mock/transformer/index.js:1:36027)
      at d (node_modules/ts-auto-mock/transformer/index.js:1:34914)
      at Object.t.GetMockPropertiesFromSymbol (node_modules/ts-auto-mock/transformer/index.js:1:35067)
      at Object.t.GetProperties (node_modules/ts-auto-mock/transformer/index.js:1:44403)
      at Object.t.GetClassDeclarationDescriptor (node_modules/ts-auto-mock/transformer/index.js:1:12407)

**Comment by Pmyl** [comment]
this is working for me

```ts
import { computed, observable } from 'mobx';
import { createMock } from 'ts-auto-mock';

class ClassUnderTest {
  @observable
  public a: number = 3;
  @observable
  public b: number = 4;

  @computed
  public get computedProp(): number {
    return this.a + this.b;
  }

  public get notComputedProp(): number {
    return this.a + this.b;
  }
}

it('should work', () => {
  const mock: ClassUnderTest = createMock<ClassUnderTest>();
  expect(mock).toBeDefined();

  expect(mock.computedProp).toBeDefined();
  expect(mock.notComputedProp).toBeDefined();

  expect(mock.a).toBeDefined();
  expect(mock.b).toBeDefined();
});
```

could you provide an example of failing class?

**Comment by dziadyk-m** [comment]
Thank you, for your effort. You're right. Problem in my case was related with store dependencies, deep down one of the property was still a plain js class and that caused this error . Issue can be closed, sorry for the confusion :)

**Comment by Pmyl** [comment]
No worries, happy that the issue was found :D
